#!/bin/bash
#
# Pre-push hook verifying that inappropriate code will not be pushed.

# Colors for the terminal output
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check that prettier formatting rules are not violated.
if ! zk_supervisor fmt --check; then
    echo -e "${RED}Push error!${NC}"
    echo "Please format the code via 'zks fmt', cannot push unformatted code"
    exit 1
fi
