#!/bin/bash
#
# Pre-push hook verifying that inappropriate code will not be pushed.

# Colors for the terminal output
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check that prettier formatting rules are not violated.
if which zkstack >/dev/null; then
  if ! zkstack dev fmt --check; then
      echo -e "${RED}Push error!${NC}"
      echo "Please format the code via 'zki dev fmt', cannot push unformatted code"
      exit 1
  fi
else
  echo "Please install ZK Stack CLI using zkstackup from https://github.com/matter-labs/zksync-era/tree/main/zkstack_cli/zkstackup, and then run ./bin/zkt from the zksync-era repository."
  exit 1
fi
