DROP INDEX IF EXISTS prover_jobs_blob_cleanup_status_index;

DROP INDEX IF EXISTS witness_inputs_blob_cleanup_status_index;

DROP INDEX IF EXISTS leaf_aggregation_witness_jobs_blob_cleanup_status_index;

DROP INDEX IF EXISTS node_aggregation_witness_jobs_blob_cleanup_status_index;

DROP INDEX IF EXISTS scheduler_witness_jobs_blob_cleanup_status_index;
