ALTER TABLE prover_fri_protocol_versions DROP COLUMN IF EXISTS recursion_node_level_vk_hash;
ALTER TABLE prover_fri_protocol_versions DROP COLUMN IF EXISTS recursion_leaf_level_vk_hash;
ALTER TABLE prover_fri_protocol_versions DROP COLUMN IF EXISTS recursion_circuits_set_vks_hash;
