name: 'Build contracts'
description: 'Builds or downloads contracts.'

runs:
  using: "composite"
  steps:

    - name: Download contracts
      shell: 'bash -ex {0}'
      run: |
        commit_sha=$(git submodule status contracts | awk '{print $1}' | tr -d '-')
        page=1
        filtered_tag=""
        while [ true ]; do
          echo "Page: $page"
          tags=$(run_retried curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/matter-labs/era-contracts/tags?per_page=100&page=${page}" | jq .)
          if [ $(jq length <<<"$tags") -eq 0 ]; then
            echo "No tag found on all pages."
            echo "BUILD_CONTRACTS=true" >> "$GITHUB_ENV"
            exit 0
          fi
          filtered_tag=$(jq -r --arg commit_sha "$commit_sha" 'map(select(.commit.sha == $commit_sha)) | .[].name' <<<"$tags")
          if [[ ! -z "$filtered_tag" ]]; then
            echo "BUILD_CONTRACTS=false" >> "$GITHUB_ENV"
            break
          fi
          ((page++))
        done
        echo "Contracts tag is: ${filtered_tag}"
        mkdir -p ./contracts
        run_retried curl -s -LO https://github.com/matter-labs/era-contracts/releases/download/${filtered_tag}/l1-contracts.tar.gz
        run_retried curl -s -LO https://github.com/matter-labs/era-contracts/releases/download/${filtered_tag}/l2-contracts.tar.gz
        run_retried curl -s -LO https://github.com/matter-labs/era-contracts/releases/download/${filtered_tag}/system-contracts.tar.gz
        tar -C ./contracts -zxf l1-contracts.tar.gz
        tar -C ./contracts -zxf l2-contracts.tar.gz
        tar -C ./contracts -zxf system-contracts.tar.gz

    - name: Build contracts
      if: ${{ env.BUILD_CONTRACTS == 'true' }}
      shell: 'bash -ex {0}'
      run: zkstack dev contracts
