{
 "title": "Consensus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "L2 block number",
   "type": "timeseries",
   "description": "Number of the latest L2 block persisted in this node's database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_block_store_next_persisted_block - 1",
     "legendFormat": "Number"
    }
   ]
  },
  {
   "title": "L1 batch number",
   "type": "timeseries",
   "description": "Number of the latest L1 batch persisted in this node's database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_batch_store_next_persisted_batch - 1",
     "legendFormat": "Number"
    }
   ]
  },
  {
   "title": "L2 block rate (blocks/min)",
   "type": "timeseries",
   "description": "Number of L2 blocks persisted in this node's database per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(zksync_consensus_storage_block_store_next_persisted_block[1m])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "L1 batch rate (batches/h)",
   "type": "timeseries",
   "description": "Number of L1 batches persisted in this node's database per hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(zksync_consensus_storage_batch_store_next_persisted_batch[1h])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Peer connections",
   "type": "timeseries",
   "description": "How many inbound and outbound connections we have to peers in the gossip network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "network_gossip_inbound_connections",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_gossip_outbound_connections",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "L1 batch attestation",
   "type": "timeseries",
   "description": "Display the number of the last sealed batch and of the last attested batch. Attested batch are sealed batches that have been signed by a quorum of attesters.\nIt also displays the last batch number for which we have at least one vote. Note that attesters might be malicious and provide votes for batches far in the future, so this metric might provide misleading results. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_batch_store_last_persisted_batch_qc",
     "legendFormat": "Attested"
    },
    {
     "expr": "zksync_consensus_storage_batch_store_next_persisted_batch-1",
     "legendFormat": "Sealed"
    },
    {
     "expr": "network_gossip_batch_votes_last_added_vote_batch_number",
     "legendFormat": "Voted"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "description": "Data received over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_received_bytes[1m])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "description": "Data sent over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_sent_bytes[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "RPC latency client",
   "type": "timeseries",
   "description": "Latency of RPC client requests, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"client_send_recv\"}[10m])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC latency server",
   "type": "timeseries",
   "description": "Latency of RPC server responses, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"server_recv_send\"}[$__rate_interval])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate client",
   "type": "timeseries",
   "description": "Rate of RPC client requests, in requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate server",
   "type": "timeseries",
   "description": "Rate of RPC server responses, in requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}