ALTER TABLE contracts ALTER COLUMN bytecode DROP NOT NULL;
ALTER TABLE contracts ALTER COLUMN tx_hash DROP NOT NULL;
ALTER TABLE contracts ALTER COLUMN miniblock_number DROP NOT NULL;
ALTER TABLE contracts ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE contracts ALTER COLUMN updated_at DROP NOT NULL;
