{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Protocol version",
   "type": "gauge",
   "description": "Protocol version that this node is running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "external_node_protocol_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(stage) (rate(server_processed_txs{stage=\"state_keeper\"}[10m]))"
    }
   ]
  },
  {
   "title": "Total disk space usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rocksdb_total_sst_size)",
     "legendFormat": "RocksDB"
    },
    {
     "expr": "sum by (job) (postgres_table_total_size_bytes)",
     "legendFormat": "PostgresSQL"
    }
   ]
  },
  {
   "title": "Last processed batch by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_fetcher_l1_batch)"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sync lag (blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_sync_lag)"
    }
   ]
  },
  {
   "title": "Transactions execution status",
   "type": "timeseries",
   "description": "The percentage of transactions that are being reverted or that are succeeding.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(status) (increase(server_state_keeper_tx_execution_result[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "L2 block number",
   "type": "timeseries",
   "description": "Number of the latest L2 block persisted in this node's database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_block_store_next_persisted_block-1",
     "legendFormat": "L2 block number"
    }
   ]
  },
  {
   "title": "L2 block rate (blocks/min)",
   "type": "timeseries",
   "description": "Number of L2 blocks persisted in this node's database per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(zksync_consensus_storage_block_store_next_persisted_block[1m])",
     "legendFormat": "L2 block number"
    }
   ]
  },
  {
   "title": "L1 batch attestation",
   "type": "timeseries",
   "description": "Display the number of the last sealed batch and of the last attested batch. Attested batch are sealed batches that have been signed by a quorum of attesters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_batch_store_last_persisted_batch_qc",
     "legendFormat": "Attested"
    },
    {
     "expr": "zksync_consensus_storage_batch_store_next_persisted_batch-1",
     "legendFormat": "Sealed"
    }
   ]
  },
  {
   "title": "Peer connections",
   "type": "timeseries",
   "description": "How many inbound and outbound connections we have to peers in the gossip network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "network_gossip_inbound_connections",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_gossip_outbound_connections",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "description": "Data received over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_received_bytes[1m])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "description": "Data sent over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_sent_bytes[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "RPC latency client",
   "type": "timeseries",
   "description": "Latency of RPC client requests, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"client_send_recv\"}[10m])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC latency server",
   "type": "timeseries",
   "description": "Latency of RPC server responses, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"server_recv_send\"}[$__rate_interval])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate client",
   "type": "timeseries",
   "description": "Rate of RPC client requests, in packets per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate server",
   "type": "timeseries",
   "description": "Rate of RPC server responses, in packets per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}