# Will work locally only after prior contracts build
# syntax=docker/dockerfile:experimental
FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/debian:bookworm-slim as builder

RUN apt-get update && apt-get install -y curl clang openssl libssl-dev gcc g++ \
    pkg-config build-essential libclang-dev linux-libc-dev liburing-dev git && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y nodejs npm && npm install --global yarn

RUN cd /usr/src && \
    git clone https://github.com/zkLinkProtocol/zksync-era.git zksync && \
    cd zksync && \
    git checkout zklink_testnet && \
    git pull origin zklink_testnet && \
    git submodule update --init --recursive

WORKDIR /usr/src/zksync

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/usr/src/zksync/bin:$PATH \
    ZKSYNC_HOME=/usr/src/zksync

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y && \
    rustup install nightly-2023-08-21 && \
    rustup default nightly-2023-08-21

RUN zk && \
    zk compiler system-contracts && \
    zk contract build

RUN cargo build --release --features=rocksdb/io-uring

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/debian:bookworm-slim

RUN apt-get update && apt-get install -y curl libpq5 liburing-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3000
EXPOSE 3031
EXPOSE 3030

COPY --from=builder /usr/src/zksync/target/release/zksync_server /usr/bin
COPY --from=builder /usr/src/zksync/target/release/block_reverter /usr/bin
COPY --from=builder /usr/src/zksync/target/release/merkle_tree_consistency_checker /usr/bin
COPY --from=builder /usr/src/zksync/contracts/system-contracts/bootloader/build/artifacts/ /contracts/system-contracts/bootloader/build/artifacts/
COPY --from=builder /usr/src/zksync/contracts/system-contracts/contracts-preprocessed/artifacts/ /contracts/system-contracts/contracts-preprocessed/artifacts/
COPY --from=builder /usr/src/zksync/contracts/system-contracts/contracts-preprocessed/precompiles/artifacts/ /contracts/system-contracts/contracts-preprocessed/precompiles/artifacts/
COPY --from=builder /usr/src/zksync/contracts/system-contracts/artifacts-zk /contracts/system-contracts/artifacts-zk
COPY --from=builder /usr/src/zksync/contracts/l1-contracts/artifacts/ /contracts/l1-contracts/artifacts/
COPY --from=builder /usr/src/zksync/contracts/l2-contracts/artifacts-zk/ /contracts/l2-contracts/artifacts-zk/
COPY etc/tokens/ /etc/tokens/
COPY etc/ERC20/ /etc/ERC20/
COPY etc/multivm_bootloaders/ /etc/multivm_bootloaders/

ENTRYPOINT ["zksync_server"]
