#!/usr/bin/env bash
set -eo pipefail

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
ZKT_DIR=${ZKT_DIR:-"$BASE_DIR/.zkt"}
ZKT_BIN_DIR="$ZKT_DIR/bin"

ZKUP_SKIP_ZK_SUPERVISOR=0

BINS=(zk_inception zk_supervisor)

main() {
  check_prerequisites
  parse_args "$@"
  mkdir -p "$ZKT_BIN_DIR"

  if [ -n "$ZKUP_PATH" ]; then
    install_local
  else
    install_from_repo
  fi

  add_to_path
  echo "zk_toolbox installed successfully"
}

PREREQUISITES=(cargo git)

check_prerequisites() {
  failed_prerequisites=()
  for prerequisite in "${PREREQUISITES[@]}"; do
    if ! check_prerequisite "$prerequisite"; then
      failed_prerequisites+=("$prerequisite")
    fi
  done
  if [ ${#failed_prerequisites[@]} -gt 0 ]; then
    echo "The following prerequisites are missing: ${failed_prerequisites[*]}"
    exit 1
  fi
}

check_prerequisite() {
  command -v "$1" &>/dev/null
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
    --)
      shift
      break
      ;;

    -p | --path)
      shift
      ZKUP_PATH=$1
      ;;
    -r | --repo)
      shift
      ZKUP_REPO=$1
      ;;
    -b | --branch)
      shift
      ZKUP_BRANCH=$1
      ;;
    -c | --commit)
      shift
      ZKUP_COMMIT=$1
      ;;
    -v | --version)
      shift
      ZKUP_VERSION=$1
      ;;
    --skip-zk-supervisor) ZKUP_SKIP_ZK_SUPERVISOR=1 ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
    esac
    shift
  done
}

usage() {
  cat 1>&2 <<EOF
zkup - zkup installer
Usage placeholder
EOF
}

install_local() {
  if [ ! -d "$ZKUP_PATH" ]; then
    echo "Path $ZKUP_PATH does not exist"
    exit 1
  fi

  if [ -n "$ZKUP_BRANCH" ] || [ -n "$ZKUP_COMMIT" ] || [ -n "$ZKUP_VERSION" ]; then
    echo "Ignoring --branch, --commit and --version arguments when installing from local path"
  fi

  echo "Installing zk_toolbox from $ZKUP_PATH"
  cd "$ZKUP_PATH"/zk_toolbox

  if [ $ZKUP_SKIP_ZK_SUPERVISOR -eq 1 ]; then
    BINS=(zk_inception)
  fi

  for bin in "${BINS[@]}"; do
    echo "Installing $bin"
    ensure cargo install --root $ZKT_DIR --path ./crates/$bin --force
  done
}

install_from_repo() {
  if [ -n "$ZKUP_PATH" ]; then
    echo "Ignoring --path argument when installing from repository"
  fi

  ZKUP_REPO=${ZKUP_REPO:-"matter-labs/zksync-era"}

  echo "Installing zk_toolbox from $ZKUP_REPO"

  if [ $ZKUP_SKIP_ZK_SUPERVISOR -eq 1 ]; then
    BINS=(zk_inception)
  fi

  if [ -n "$ZKUP_VERSION" ]; then
    if [ -n "$ZKUP_COMMIT" ] || [ -n "$ZKUP_BRANCH" ]; then
      echo "Ignoring --commit and --branch arguments when installing by version"
    fi
    ensure cargo install --root $ZKT_DIR --git "https://github.com/$ZKUP_REPO" --tag "zk_toolbox-v$ZKUP_VERSION" --locked "${BINS[@]}" --force
  elif [ -n "$ZKUP_COMMIT" ]; then
    if [ -n "$ZKUP_BRANCH" ]; then
      echo "Ignoring --branch argument when installing by commit"
    fi
    ensure cargo install --root $ZKT_DIR --git "https://github.com/$ZKUP_REPO" --rev "$ZKUP_COMMIT" --locked "${BINS[@]}" --force
  elif [ -n "$ZKUP_BRANCH" ]; then
    ensure cargo install --root $ZKT_DIR --git "https://github.com/$ZKUP_REPO" --branch "$ZKUP_BRANCH" --locked "${BINS[@]}" --force
  else
    ensure cargo install --root $ZKT_DIR --git "https://github.com/$ZKUP_REPO" --locked "${BINS[@]}" --force
  fi
}

ensure() {
  if ! "$@"; then err "command failed: $*"; fi
}

add_to_path() {
  if [[ ":$PATH:" == *":${ZKT_BIN_DIR}:"* ]]; then
    echo "zkup: found ${ZKT_BIN_DIR} in PATH"
    return 0
  fi

  case $SHELL in
  */zsh)
    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
    ;;
  */bash)
    PROFILE="$HOME/.bashrc"
    ;;
  */fish)
    PROFILE="$HOME/.config/fish/config.fish"
    ;;
  */ash)
    PROFILE="$HOME/.profile"
    ;;
  *)
    echo "zkup: could not detect shell, manually add ${ZKT_BIN_DIR} to your PATH."
    return 1
    ;;
  esac

  if [[ ! -f "$PROFILE" ]]; then
    echo "zkup: Profile file $PROFILE does not exist, creating it."
    touch "$PROFILE"
  fi

  if [[ "$SHELL" == *"/fish"* ]]; then
    echo -e "\n# Added by zkup\nfish_add_path -a $ZKT_BIN_DIR" >>"$PROFILE"
    echo "zkup: Added $ZKT_BIN_DIR to PATH in $PROFILE using fish_add_path."
  else
    echo -e "\n# Added by zkup\nexport PATH=\"\$PATH:$ZKT_BIN_DIR\"" >>"$PROFILE"
    echo "zkup: Added $ZKT_BIN_DIR to PATH in $PROFILE."
  fi
}

main "$@"
