{
 "title": "General",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Protocol version",
   "type": "gauge",
   "description": "Protocol version that this node is running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "external_node_protocol_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rocksdb_total_sst_size)",
     "legendFormat": "RocksDB"
    },
    {
     "expr": "sum by (job) (postgres_table_total_size_bytes)",
     "legendFormat": "PostgresSQL"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(stage) (rate(server_processed_txs{stage=\"state_keeper\"}[10m]))"
    }
   ]
  },
  {
   "title": "Priority TPS",
   "type": "stat",
   "description": "Priority transactions (aka L1 transactions) per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(stage) (rate(server_processed_l1_txs{stage=\"state_keeper\"}[10m]))"
    }
   ]
  },
  {
   "title": "Last processed batch by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_fetcher_l1_batch)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "L1 batch sync lag",
   "type": "timeseries",
   "description": "Shows the batch numbers on the local node and the server node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(stage) (external_node_fetcher_l1_batch{stage=\"open\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "zksync_consensus_storage_batch_store_next_persisted_batch",
     "legendFormat": "Local"
    }
   ]
  },
  {
   "title": "Transactions execution status",
   "type": "timeseries",
   "description": "The number of transactions that are being reverted or that are succeeding.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status) (increase(server_state_keeper_tx_execution_result[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 blocks sync lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (stage) (external_node_sync_lag)"
    }
   ]
  },
  {
   "title": "Avg number of transactions in L2 block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(server_state_keeper_miniblock_transactions_in_miniblock_sum[5m]) / increase(server_state_keeper_miniblock_transactions_in_miniblock_count[5m])",
     "legendFormat": "Number"
    }
   ]
  },
  {
   "title": "Transactions execution status (%)",
   "type": "timeseries",
   "description": "The percentage of transactions that are being reverted or that are succeeding.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(status) (increase(server_state_keeper_tx_execution_result[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg number of transactions in L1 batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(server_state_keeper_l1_batch_transactions_in_l1_batch_sum[1h]) / increase(server_state_keeper_l1_batch_transactions_in_l1_batch_count[1h])",
     "legendFormat": "Number"
    }
   ]
  }
 ]
}