DROP TABLE IF EXISTS basic_witness_input_producer_jobs;

DROP INDEX IF EXISTS idx_basic_witness_input_producer_jobs_status;
DROP INDEX IF EXISTS idx_basic_witness_input_producer_jobs_attempts_processing_status;
DROP INDEX IF EXISTS idx_basic_witness_input_producer_jobs_time;
