ALTER TABLE tee_proof_generation_details DROP CONSTRAINT IF EXISTS tee_proof_generation_details_pubkey_fkey;
ALTER TABLE tee_proof_generation_details RENAME TO airbender_proof_generation_details;
DROP TABLE IF EXISTS tee_attestations;
