name: Build zksync-runtime-base Docker image
on:
  workflow_dispatch:
    inputs:
      repo_ref:
        description: "git reference of the zksync-era to build"
        required: true
        default: main
jobs:
  build-images:
    name: Build and Push Docker Images
    runs-on: matterlabs-ci-runner-high-performance
    outputs:
      image_tag_sha: ${{ steps.get-sha.outputs.image_tag_sha }}
    # Needed to push to Gihub Package Registry
    permissions:
      packages: write
      contents: read
    env:
      REPO_REF: ${{ github.event.inputs.repo_ref }}
    strategy:
      matrix:
        name: [ runtime-base ]
        image_name: [ zksync-runtime-base ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: "recursive"

      - name: Login to google container registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get-sha
        run: |
          echo IMAGE_TAG_SHA=$(git rev-parse --short HEAD) >> $GITHUB_ENV
          echo image_tag_sha=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          context: .
          platforms: arm64, amd64
          file: docker/${{ matrix.name }}/Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/matter-labs/zksync-era
            org.opencontainers.image.licenses="MIT OR Apache-2.0"
          tags: |
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/${{ matrix.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
