name: Build zksync-runtime-base Docker image
on:
  workflow_dispatch:
    inputs:
      repo_ref:
        description: "git reference of the zksync-era to build"
        required: true
        default: main
jobs:
  build-images:
    name: Build and Push Docker Images
    runs-on: matterlabs-ci-runner-high-performance
    outputs:
      image_tag_sha: ${{ steps.get-sha.outputs.image_tag_sha }}
    # Needed to push to Gihub Package Registry
    permissions:
      packages: write
      contents: read
    env:
      REPO_REF: ${{ github.event.inputs.repo_ref }}
    strategy:
      matrix:
        name: [ runtime-base ]
        image_name: [ zksync-runtime-base ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "recursive"

      - name: Login to google container registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get-sha
        run: |
          echo IMAGE_TAG_SHA=$(git rev-parse --short HEAD) >> $GITHUB_ENV
          echo image_tag_sha=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true
          context: .
          platforms: arm64, amd64
          file: docker/${{ matrix.name }}/Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/matter-labs/zksync-era
            org.opencontainers.image.licenses="MIT OR Apache-2.0"
          tags: |
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/${{ matrix.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
