name: Cargo license check
on: pull_request
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
      with:
        manifest-path: "./core/Cargo.toml"
        command: check
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
