name: Cargo license check
on: pull_request
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
      with:
        manifest-path: "./core/Cargo.toml"
        command: check
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
