name: Cargo license check
on: pull_request
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: EmbarkStudios/cargo-deny-action@76cd80eb775d7bbbd2d80292136d74d39e1b4918 # v2.0.11
      with:
        manifest-path: "./core/Cargo.toml"
        command: check
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
