name: Lint

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

#  lint:
#    runs-on: matterlabs-ci-runner-highmem-long
#    env:
#      ZKSYNC_HOME: ${{ github.workspace }}
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: "recursive"
#
#      - name: Update path
#        run: echo $(pwd)/bin >> $GITHUB_PATH
#
#      - name: Start services
#        run: ci_localnet_up
#
#      - name: Install zkstack
#        run: |
#          ci_run git config --global --add safe.directory /usr/src/zksync
#          ci_run ./zkstack_cli/zkstackup/install -g --path ./zkstack_cli/zkstackup/zkstackup
#          ci_run zkstackup -g --local
#
#      - name: Build
#        run: ci_run yarn install
#
#      - name: Format
#        run: ci_run zkstack dev fmt --check
#
#      - name: Lint
#        run: ci_run zkstack dev lint --check
#
#      - name: Check Database
#        env:
#          PROVER_URL: 'postgres://postgres:notsecurepassword@localhost:5432/zksync_local_prover'
#          CORE_URL: 'postgres://postgres:notsecurepassword@localhost:5432/zksync_local'
#        run: |
#          ci_run zkstack dev db setup --prover-url=${{ env.PROVER_URL }} --core-url=${{ env.CORE_URL }}
#          ci_run zkstack dev database check-sqlx-data --prover-url=${{ env.PROVER_URL }} --core-url=${{ env.CORE_URL }}

  lint-docker:
    runs-on: matterlabs-ci-runner-highmem-long
    container:
      image: ghcr.io/matter-labs/zk-environment:latest2.0-lightweight
      env:
        SCCACHE_CACHE_SIZE: 50g
        SCCACHE_GCS_BUCKET: matterlabs-infra-sccache-storage
        SCCACHE_GCS_SERVICE_ACCOUNT: gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com
        SCCACHE_GCS_RW_MODE: READ_WRITE
        # ZKSYNC_USE_CUDA_STUBS: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update path
        run: |
          git config --global --add safe.directory '*'
          echo $(pwd)/bin >> ${GITHUB_PATH}

      - name: Install zkstack
        run: |
          ./zkstack_cli/zkstackup/install -g --path ./zkstack_cli/zkstackup/zkstackup
          zkstackup -g --local

      - name: Build contracts
        working-directory: contracts
        run: yarn install

      - name: Format
        run: zkstack dev fmt --check

      - name: Lint
        run: zkstack dev lint --check
