name: Publish crates

on:
  push:
    branches:
      - release-please--branches--main--components--core
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to release. Possible values are: core, prover or zkstack_cli.'
        required: true
        default: 'zkstack_cli'
      run-build:
        type: boolean
        description: 'Build the workspace before release.'
        required: false
        default: true
      run-tests:
        type: boolean
        description: 'Run tests before release.'
        required: false
        default: false


jobs:

  publish-crates:
    name: Publish to crates.io
    runs-on: matterlabs-ci-runner-highdisk
    env:
      ZKSYNC_USE_CUDA_STUBS: true
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Publish crates
        uses: matter-labs/zksync-ci-common/.github/actions/publish-crates@c488e5a187bfa5b667ec31061045be3ad7f3245a
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }} # Slack webhook for notifications
          workspace_path: ${{ inputs.component || 'core' }}
          run_build: ${{ inputs.run-build }}
          run_tests: ${{ inputs.run-tests }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          dependencies: 'clang libclang-dev'
          dry_run: ${{ github.event_name == 'push' }}
          notify_slack: ${{ github.event_name != 'push' }}
